// Post index is auto-generated by scripts/build-content.ts from the blog repo.
// Do not edit posts.generated.ts directly — edit markdown in OpenSourceWTF/blog.
export type { BlogPostMeta } from "./posts.generated";
export { postIndex } from "./posts.generated";
import { postIndex } from "./posts.generated";
import type { BlogPostMeta } from "./posts.generated";

export interface BlogPost extends BlogPostMeta {
  content: string;
  html: string;
}

export async function fetchPost(slug: string): Promise<BlogPost | null> {
  try {
    const meta = postIndex.find((p) => p.slug === slug);
    if (!meta) return null;

    const res = await fetch(`/content/blog/${slug}.html`);
    if (!res.ok) return null;
    const html = await res.text();

    return { ...meta, content: "", html };
  } catch {
    return null;
  }
}
