// Post index is auto-generated by scripts/build-content.ts from the blog repo.
// Do not edit posts.generated.ts directly — edit markdown in OpenSourceWTF/blog.
export type { BlogPostMeta } from "./posts.generated";
export { postIndex } from "./posts.generated";
import { postIndex } from "./posts.generated";
import type { BlogPostMeta } from "./posts.generated";

export interface BlogPost extends BlogPostMeta {
  content: string;
  html: string;
}

export async function fetchPost(slug: string): Promise<BlogPost | null> {
  try {
    const res = await fetch(`/content/blog/${slug}.md`);
    if (!res.ok) return null;
    const raw = await res.text();

    // Strip frontmatter
    const fmMatch = raw.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/);
    const body = fmMatch ? fmMatch[1].trim() : raw;

    const meta = postIndex.find((p) => p.slug === slug);
    if (!meta) return null;

    const { marked } = await import("marked");
    const html = await marked(body);

    return { ...meta, content: body, html };
  } catch {
    return null;
  }
}
