/**
 * build-content.ts
 *
 * Reads markdown blog posts from the blog repo (or local fallback),
 * then generates:
 *   - src/content/posts.generated.ts  (typed post index)
 *   - public/content/blog/*.md        (raw markdown for agent access)
 *   - public/content/blog/*.html      (pre-rendered HTML for client)
 *   - public/rss.xml                  (RSS 2.0 feed)
 *   - public/sitemap.xml              (sitemap for SEO)
 *   - public/llms.txt                 (AI agent discovery file)
 */

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { marked } from "marked";

const SITE_URL = "https://opensource.wtf";
const SITE_TITLE = "Opensource.wtf";
const SITE_DESCRIPTION =
  "Open source tools for the AI agent ecosystem. Building developer tools in the open.";

// Where to find blog posts — CI checks out to blog-content/, local dev may use ../blog/
const BLOG_SOURCES = [
  path.resolve("blog-content/posts"),
  path.resolve("../blog/posts"),
];

const OUT_PUBLIC_BLOG = path.resolve("public/content/blog");
const OUT_GENERATED_TS = path.resolve("src/content/posts.generated.ts");

interface PostMeta {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  tags: string[];
}

function findBlogDir(): string | null {
  for (const dir of BLOG_SOURCES) {
    if (fs.existsSync(dir)) return dir;
  }
  return null;
}

async function readPosts(blogDir: string): Promise<PostMeta[]> {
  const files = fs
    .readdirSync(blogDir)
    .filter((f) => f.endsWith(".md"))
    .sort();

  const posts: PostMeta[] = [];

  for (const file of files) {
    const raw = fs.readFileSync(path.join(blogDir, file), "utf-8");
    const { data, content } = matter(raw);

    const slug = file.replace(/\.md$/, "");
    posts.push({
      slug,
      title: data.title || slug,
      date: data.date || new Date().toISOString().split("T")[0],
      excerpt: data.excerpt || "",
      tags: Array.isArray(data.tags) ? data.tags : [],
    });

    // Copy raw markdown for agent access
    fs.copyFileSync(
      path.join(blogDir, file),
      path.join(OUT_PUBLIC_BLOG, file),
    );

    // Render markdown to HTML and write alongside the .md
    const body = content.trim().replace(/^# .+\n*/, ""); // strip leading h1
    const html = await marked(body);
    fs.writeFileSync(
      path.join(OUT_PUBLIC_BLOG, `${slug}.html`),
      html,
    );
  }

  // Sort newest first
  posts.sort((a, b) => b.date.localeCompare(a.date));
  return posts;
}

function generatePostsTs(posts: PostMeta[]): void {
  const code = `// AUTO-GENERATED by scripts/build-content.ts — do not edit
export interface BlogPostMeta {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  tags: string[];
}

export const postIndex: BlogPostMeta[] = ${JSON.stringify(posts, null, 2)};
`;
  fs.writeFileSync(OUT_GENERATED_TS, code);
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function generateRss(posts: PostMeta[]): void {
  const items = posts
    .map(
      (p) => `    <item>
      <title>${escapeXml(p.title)}</title>
      <link>${SITE_URL}/blog/${p.slug}</link>
      <guid>${SITE_URL}/blog/${p.slug}</guid>
      <pubDate>${new Date(p.date).toUTCString()}</pubDate>
      <description>${escapeXml(p.excerpt)}</description>
    </item>`,
    )
    .join("\n");

  const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${escapeXml(SITE_TITLE)}</title>
    <link>${SITE_URL}</link>
    <description>${escapeXml(SITE_DESCRIPTION)}</description>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <atom:link href="${SITE_URL}/rss.xml" rel="self" type="application/rss+xml"/>
${items}
  </channel>
</rss>
`;
  fs.writeFileSync(path.resolve("public/rss.xml"), rss);
}

function generateSitemap(posts: PostMeta[]): void {
  const staticPages = ["", "/projects", "/blog", "/about"];
  const blogPages = posts.map((p) => `/blog/${p.slug}`);
  const allPages = [...staticPages, ...blogPages];

  const urls = allPages
    .map(
      (pg) => `  <url>
    <loc>${SITE_URL}${pg}</loc>
    <lastmod>${new Date().toISOString().split("T")[0]}</lastmod>
  </url>`,
    )
    .join("\n");

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
  fs.writeFileSync(path.resolve("public/sitemap.xml"), sitemap);
}

function generateLlmsTxt(posts: PostMeta[]): void {
  const postLinks = posts
    .map((p) => `- [${p.title}](${SITE_URL}/content/blog/${p.slug}.md): ${p.excerpt}`)
    .join("\n");

  const llms = `# opensource.wtf

> Open source tools for the AI agent ecosystem.

## About

OpenSourceWTF builds open source developer tools focused on AI agents, automation, and modern workflows. Everything is open source with no premium tiers.

## Projects

- [Capybara](https://github.com/OpenSourceWTF/capybara): AI-powered agent framework for building agents that reason, plan, and execute complex tasks.
- [WAAAH](https://github.com/OpenSourceWTF/WAAAH): Workflow automation system for orchestrating AI agents. Define tasks, manage state, let agents handle the rest.
- [Dojo](https://github.com/OpenSourceWTF/dojo): Skill registry and distribution system for AI coding agents. Learn, share, and reuse skills.

## Links

- Website: ${SITE_URL}
- GitHub: https://github.com/OpenSourceWTF
- Blog: ${SITE_URL}/blog
- RSS: ${SITE_URL}/rss.xml

## Blog Posts

${postLinks}
`;
  fs.writeFileSync(path.resolve("public/llms.txt"), llms);
}

// --- Main ---

async function main() {
  const blogDir = findBlogDir();
  if (!blogDir) {
    console.warn(
      "⚠ No blog content found. Checked:",
      BLOG_SOURCES.join(", "),
    );
    console.warn("  Generating empty post index.");

    fs.mkdirSync(OUT_PUBLIC_BLOG, { recursive: true });
    generatePostsTs([]);
    generateRss([]);
    generateSitemap([]);
    generateLlmsTxt([]);
  } else {
    console.log(`📝 Found blog content at: ${blogDir}`);
    fs.mkdirSync(OUT_PUBLIC_BLOG, { recursive: true });

    const posts = await readPosts(blogDir);
    console.log(`   ${posts.length} post(s) found`);

    generatePostsTs(posts);
    console.log("   ✓ src/content/posts.generated.ts");

    generateRss(posts);
    console.log("   ✓ public/rss.xml");

    generateSitemap(posts);
    console.log("   ✓ public/sitemap.xml");

    generateLlmsTxt(posts);
    console.log("   ✓ public/llms.txt");

    console.log("✅ Content build complete");
  }
}

main();
